kind: pipeline
type: exec
name: default

steps:
  - name: Build and Serve
    commands:
      - npm install
      - npm run build
      - npm install -g serve
      - docker build . -t judge-cms
      - docker rm -f judge-cms || echo "Container judge-cms not found, launch a new one."
      - docker run --rm -d --name judge-cms -p 5000:5000 judge-cms

